version: "3.9"

services:
  app:
    build: .
    container_name: memory-plus-app
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    expose:
      - "8086"
    restart: unless-stopped

  nginx:
    image: nginx:1.25
    container_name: memory-plus-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    restart: unless-stopped


